version: '3.9'

services:
  django:
    container_name: LIGGIN_django
    build:
      context: .
      dockerfile: Dockerfile     
    command: python manage.py runserver 0.0.0.0:8000    
    ports:
        - 8000    
    volumes:
        - ./src:/usr/src/app 
        - /var/run/docker.sock:/var/run/docker.sock  
    networks:
        - LIGGIN

networks:
    LIGGIN:
       driver: bridge
