# Generated by Django 5.0.3 on 2024-10-25 19:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_handler', '0002_lg_algorithm_score_lg_prediction_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='lg_algorithm_performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_name', models.CharField(max_length=100, unique=True)),
                ('average_execution_time', models.FloatField(default=0.0)),
                ('total_executions', models.IntegerField(default=0)),
                ('fastest_execution', models.FloatField(default=0.0)),
                ('slowest_execution', models.FloatField(default=0.0)),
                ('last_execution_time', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('memory_usage', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'lg_algorithm_performance',
            },
        ),
        migrations.CreateModel(
            name='lg_performance_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_name', models.CharField(max_length=100)),
                ('execution_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('execution_time', models.FloatField()),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lg_performance_history',
            },
        ),
    ]
