# Generated by Django 4.2.6 on 2023-11-12 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lg_lottery_algorithm_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_type', models.CharField(max_length=50)),
                ('algorithm_type_description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='lg_lottery_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=50, null=True)),
                ('lottery_type', models.CharField(max_length=50, null=True)),
                ('lottery_type_description', models.CharField(max_length=50, null=True)),
                ('image_url', models.CharField(max_length=50, null=True)),
                ('min_number', models.IntegerField()),
                ('max_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='lg_lottery_winner_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lottery_type_number', models.JSONField()),
                ('lottery_type_number_date', models.DateField()),
                ('lottery_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algorithms.lg_lottery_type')),
            ],
        ),
    ]
