# Generated by Django 4.2.6 on 2023-11-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lg_lottery_type',
            name='skip_items',
            field=models.IntegerField(null=True),
        ),
    ]
