# Generated by Django 4.2.6 on 2023-11-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0002_lg_lottery_type_skip_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lg_lottery_winner_number',
            name='lottery_type_number_date',
        ),
        migrations.AddField(
            model_name='lg_lottery_winner_number',
            name='lottery_type_number_week',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lg_lottery_winner_number',
            name='lottery_type_number_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterModelTable(
            name='lg_lottery_algorithm_type',
            table='lg_lottery_algorithm_type',
        ),
        migrations.AlterModelTable(
            name='lg_lottery_type',
            table='lg_lottery_type',
        ),
        migrations.AlterModelTable(
            name='lg_lottery_winner_number',
            table='lg_lottery_winner_number',
        ),
    ]
