# Generated by Django 4.2.6 on 2023-11-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0004_lg_lottery_winner_number_average_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lg_lottery_type',
            name='pieces_of_draw_numbers',
            field=models.IntegerField(null=True),
        ),
    ]
