# Generated by Django 4.2.6 on 2023-11-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0005_lg_lottery_type_pieces_of_draw_numbers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='lg_lottery_algorithm_type',
        ),
        migrations.AddField(
            model_name='lg_lottery_type',
            name='draw_day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lg_lottery_type',
            name='draw_time',
            field=models.TimeField(null=True),
        ),
    ]
