# Generated by Django 5.0.3 on 2024-10-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0006_delete_lg_lottery_algorithm_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lg_lottery_type',
            name='additional_max_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lg_lottery_type',
            name='additional_min_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lg_lottery_type',
            name='additional_numbers_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lg_lottery_type',
            name='has_additional_numbers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lg_lottery_winner_number',
            name='additional_numbers',
            field=models.JSONField(null=True),
        ),
    ]
